import { buildTopic, dialogue, raw, type TopicSeed } from "./helpers";

const seeds: TopicSeed[] = [
  {
    id: "photography-cameras",
    title: "Photography & Cameras",
    shortTitle: "Photography",
    description: "Discuss equipment, ask permission, find viewpoints, and solve camera problems.",
    category: "interests",
    domain: raw(
      ["camera", "カメラ", "カメラ", "kamera"],
      ["camera body", "カメラボディ", "カメラボディ", "kamera bodi"],
      ["lens", "レンズ", "レンズ", "renzu"],
      ["battery", "バッテリー", "バッテリー", "batterii", "noun", "", "batterī"],
      ["charger", "じゅうでんき", "充電器", "juudenki", "noun", "", "jūdenki"],
      ["memory card", "メモリーカード", "メモリーカード", "memorii kaado", "noun", "", "memorī kādo"],
      ["tripod", "さんきゃく", "三脚", "sankyaku"],
      ["flash", "フラッシュ", "フラッシュ", "furasshu"],
      ["viewfinder", "ファインダー", "ファインダー", "faindaa", "noun", "", "faindā"],
      ["monitor", "モニター", "モニター", "monitaa", "noun", "", "monitā"],
      ["shutter", "シャッター", "シャッター", "shattaa", "noun", "", "shattā"],
      ["aperture", "しぼり", "絞り", "shibori"],
      ["ISO sensitivity", "アイエスオーかんど", "ISO感度", "ai esu oo kando", "noun", "", "ai esu ō kando"],
      ["exposure", "ろしゅつ", "露出", "roshutsu"],
      ["focus", "ピント", "ピント", "pinto"],
      ["autofocus", "オートフォーカス", "オートフォーカス", "ooto fookasu", "noun", "", "ōto fōkasu"],
      ["manual focus", "マニュアルフォーカス", "マニュアルフォーカス", "manyuaru fookasu", "noun", "", "manyuaru fōkasu"],
      ["zoom", "ズーム", "ズーム", "zuumu", "noun", "", "zūmu"],
      ["wide-angle lens", "こうかくレンズ", "広角レンズ", "koukaku renzu", "noun", "", "kōkaku renzu"],
      ["telephoto lens", "ぼうえんレンズ", "望遠レンズ", "bouen renzu", "noun", "", "bōen renzu"],
      ["prime lens", "たんしょうてんレンズ", "単焦点レンズ", "tanshouten renzu", "noun", "", "tanshōten renzu"],
      ["filter", "フィルター", "フィルター", "firutaa", "noun", "", "firutā"],
      ["lens hood", "レンズフード", "レンズフード", "renzu fuudo", "noun", "", "renzu fūdo"],
      ["camera strap", "カメラストラップ", "カメラストラップ", "kamera sutorappu"],
      ["camera bag", "カメラバッグ", "カメラバッグ", "kamera baggu"],
      ["sensor", "センサー", "センサー", "sensaa", "noun", "", "sensā"],
      ["full-frame camera", "フルサイズカメラ", "フルサイズカメラ", "furu saizu kamera"],
      ["mirrorless camera", "ミラーレスカメラ", "ミラーレスカメラ", "miraaresu kamera", "noun", "", "mirāresu kamera"],
      ["digital SLR", "いちがんレフ", "一眼レフ", "ichigan refu"],
      ["compact camera", "コンパクトカメラ", "コンパクトカメラ", "konpakuto kamera"],
      ["film camera", "フィルムカメラ", "フィルムカメラ", "firumu kamera"],
      ["film", "フィルム", "フィルム", "firumu"],
      ["development", "げんぞう", "現像", "genzou", "noun", "", "genzō"],
      ["print", "プリント", "プリント", "purinto"],
      ["photograph", "しゃしん", "写真", "shashin"],
      ["video", "どうが", "動画", "douga", "noun", "", "dōga"],
      ["microphone", "マイク", "マイク", "maiku"],
      ["gimbal", "ジンバル", "ジンバル", "jinbaru"],
      ["image stabilization", "てぶれほせい", "手ぶれ補正", "tebure hosei"],
      ["resolution", "かいぞうど", "解像度", "kaizoudo", "noun", "", "kaizōdo"],
      ["RAW file", "ローファイル", "RAWファイル", "roo fairu", "noun", "", "rō fairu"],
      ["JPEG file", "ジェイペグファイル", "JPEGファイル", "jeipegu fairu"],
      ["white balance", "ホワイトバランス", "ホワイトバランス", "howaito baransu"],
      ["composition", "こうず", "構図", "kouzu", "noun", "", "kōzu"],
      ["portrait", "じんぶつしゃしん", "人物写真", "jinbutsu shashin"],
      ["landscape", "ふうけいしゃしん", "風景写真", "fuukei shashin", "noun", "", "fūkei shashin"],
      ["night view", "やけい", "夜景", "yakei"],
      ["sunrise", "ひので", "日の出", "hinode"],
      ["sunset", "ゆうやけ", "夕焼け", "yuuyake", "noun", "", "yūyake"],
      ["backlight", "ぎゃっこう", "逆光", "gyakkou", "noun", "", "gyakkō"],
      ["reflection", "うつりこみ", "映り込み", "utsurikomi"],
      ["photography permission", "さつえいきょか", "撮影許可", "satsuei kyoka"],
      ["no photography", "さつえいきんし", "撮影禁止", "satsuei kinshi"],
      ["no tripods", "さんきゃくきんし", "三脚禁止", "sankyaku kinshi"],
      ["no flash", "フラッシュきんし", "フラッシュ禁止", "furasshu kinshi"],
      ["viewpoint", "てんぼうスポット", "展望スポット", "tenbou supotto", "noun", "", "tenbō supotto"],
      ["camera shop", "カメラてん", "カメラ店", "kamera ten"],
      ["repair", "しゅうり", "修理", "shuuri", "noun", "", "shūri"],
      ["rental", "レンタル", "レンタル", "rentaru"],
      ["photo studio", "しゃしんかん", "写真館", "shashinkan"],
      ["shutter speed", "シャッタースピード", "シャッタースピード", "shattaa supiido", "noun", "", "shattā supīdo"],
      ["focal length", "しょうてんきょり", "焦点距離", "shouten kyori", "noun", "", "shōten kyori"],
      ["depth of field", "ひしゃかいしんど", "被写界深度", "hishakai shindo"],
      ["exposure compensation", "ろしゅつほせい", "露出補正", "roshutsu hosei"],
      ["metering", "そっこう", "測光", "sokkou", "noun", "", "sokkō"],
      ["burst shooting", "れんしゃ", "連写", "rensha"],
      ["self-timer", "セルフタイマー", "セルフタイマー", "serufu taimaa", "noun", "", "serufu taimā"],
      ["silent shutter", "サイレントシャッター", "サイレントシャッター", "sairento shattaa", "noun", "", "sairento shattā"],
      ["rolling shutter", "ローリングシャッター", "ローリングシャッター", "rooringu shattaa", "noun", "", "rōringu shattā"],
      ["dynamic range", "ダイナミックレンジ", "ダイナミックレンジ", "dainamikku renji"],
      ["image noise", "ノイズ", "ノイズ", "noizu"],
      ["blown highlights", "しろとび", "白飛び", "shirotobi"],
      ["crushed shadows", "くろつぶれ", "黒つぶれ", "kurotsubure"],
      ["color profile", "カラープロファイル", "カラープロファイル", "karaa purofairu", "noun", "", "karā purofairu"],
      ["backup", "バックアップ", "バックアップ", "bakkuappu"],
      ["card full", "ようりょうぶそく", "容量不足", "youryou busoku", "phrase", "", "yōryō busoku"],
      ["spare battery", "よびバッテリー", "予備バッテリー", "yobi batterii", "noun", "", "yobi batterī"],
      ["lens cleaning", "レンズクリーニング", "レンズクリーニング", "renzu kuriiningu", "noun", "", "renzu kurīningu"],
      ["rain cover", "レインカバー", "レインカバー", "rein kabaa", "noun", "", "rein kabā"],
      ["consent to photograph", "さつえいのどうい", "撮影の同意", "satsuei no doui", "noun", "", "satsuei no dōi"]
    ),
    slotMeanings: [
      "camera", "camera body", "lens", "battery", "charger", "memory card", "tripod", "flash", "viewfinder", "monitor",
      "shutter", "autofocus", "manual focus", "zoom", "wide-angle lens", "telephoto lens", "prime lens", "filter",
      "lens hood", "camera strap", "camera bag", "microphone", "gimbal", "image stabilization", "self-timer",
      "silent shutter", "exposure compensation", "rain cover"
    ],
    dialogues: [
      dialogue("photo-permission", "Asking permission", "Inside a temple", [
        ["traveler", "May I take photos here?", "ここで写真を撮ってもいいですか。", "ここで写真を撮ってもいい？"],
        ["local", "Yes, but please do not use flash.", "はい、ただしフラッシュは使わないでください。", "うん、でもフラッシュは使わないで。"],
        ["traveler", "May I use a tripod?", "三脚を使ってもいいですか。", "三脚を使ってもいい？"],
        ["local", "Tripods are not allowed inside.", "堂内では三脚は禁止です。", "中では三脚は禁止。"]
      ]),
      dialogue("photo-viewpoint", "Finding a viewpoint", "Before sunset", [
        ["traveler", "Where is a good sunset viewpoint?", "夕日のきれいな展望スポットはどこですか。", "夕日のきれいな展望スポットはどこ？"],
        ["local", "The hill behind the shrine is best.", "神社の裏の丘がおすすめです。", "神社の裏の丘がおすすめ。"],
        ["traveler", "Can I walk there from here?", "ここから歩いて行けますか。", "ここから歩いて行ける？"],
        ["local", "Yes, it takes about fifteen minutes.", "はい、15分くらいです。", "うん、15分くらい。"]
      ]),
      dialogue("photo-repair", "A camera problem", "At a camera shop", [
        ["traveler", "My camera will not turn on.", "カメラの電源が入りません。", "カメラの電源が入らない。"],
        ["local", "May I check the battery?", "バッテリーを確認してもいいですか。", "バッテリーを確認してもいい？"],
        ["traveler", "Yes. Can it be repaired today?", "はい。今日中に修理できますか。", "うん。今日中に修理できる？"],
        ["local", "We can replace the battery immediately.", "バッテリー交換ならすぐできます。", "バッテリー交換ならすぐできるよ。"]
      ])
    ],
    sentence: {
      english: "May I use the {meaning}?",
      formal: "{term}を使ってもいいですか",
      informal: "{term}を使ってもいい？"
    },
    response: {
      promptFormal: "{term}が必要ですか",
      promptInformal: "{term}が必要？",
      answerFormal: "はい、{term}が必要です",
      answerInformal: "うん、{term}が必要"
    }
  },
  {
    id: "aircraft-jsdf",
    title: "Aircraft & Japanese Military Aviation",
    shortTitle: "Aircraft",
    description: "Recognize military aircraft roles, airframe parts, and aircraft operated by Japan's Self-Defense Forces.",
    category: "interests",
    domain: raw(
      ["military aircraft", "ぐんようき", "軍用機", "gunyouki", "noun", "", "gunyōki"],
      ["fighter aircraft", "せんとうき", "戦闘機", "sentouki", "noun", "", "sentōki"],
      ["interceptor", "げいげきき", "迎撃機", "geigekiki"],
      ["multirole fighter", "たようとせんとうき", "多用途戦闘機", "tayouto sentouki", "noun", "", "tayōto sentōki"],
      ["transport aircraft", "ゆそうき", "輸送機", "yusouki", "noun", "", "yusōki"],
      ["tanker aircraft", "くうちゅうきゅうゆき", "空中給油機", "kuuchuu kyuuyuki", "noun", "", "kūchū kyūyuki"],
      ["airborne early warning aircraft", "そうきけいかいき", "早期警戒機", "souki keikaiki", "noun", "", "sōki keikaiki"],
      ["airborne warning and control aircraft", "そうきけいかいかんせいき", "早期警戒管制機", "souki keikai kanseiki", "noun", "", "sōki keikai kanseiki"],
      ["reconnaissance aircraft", "ていさつき", "偵察機", "teisatsuki"],
      ["maritime patrol aircraft", "しょうかいき", "哨戒機", "shoukaiki", "noun", "", "shōkaiki"],
      ["trainer aircraft", "れんしゅうき", "練習機", "renshuuki", "noun", "", "renshūki"],
      ["rescue aircraft", "きゅうなんき", "救難機", "kyuunanki", "noun", "", "kyūnanki"],
      ["utility aircraft", "たようとき", "多用途機", "tayoutoki", "noun", "", "tayōtoki"],
      ["liaison aircraft", "れんらくき", "連絡機", "renrakuki"],
      ["flight inspection aircraft", "ひこうてんけんき", "飛行点検機", "hikou tenkenki", "noun", "", "hikō tenkenki"],
      ["helicopter", "ヘリコプター", "ヘリコプター", "herikoputaa", "noun", "", "herikoputā"],
      ["attack helicopter", "こうげきヘリコプター", "攻撃ヘリコプター", "kougeki herikoputaa", "noun", "", "kōgeki herikoputā"],
      ["transport helicopter", "ゆそうヘリコプター", "輸送ヘリコプター", "yusou herikoputaa", "noun", "", "yusō herikoputā"],
      ["rescue helicopter", "きゅうなんヘリコプター", "救難ヘリコプター", "kyuunan herikoputaa", "noun", "", "kyūnan herikoputā"],
      ["patrol helicopter", "しょうかいヘリコプター", "哨戒ヘリコプター", "shoukai herikoputaa", "noun", "", "shōkai herikoputā"],
      ["amphibious aircraft", "すいりくりょうようき", "水陸両用機", "suiriku ryouyouki", "noun", "", "suiriku ryōyōki"],
      ["uncrewed aircraft", "むそうじゅうしゃこうくうき", "無操縦者航空機", "musoujuusha koukuuki", "noun", "無人航空機", "musōjūsha kōkūki"],
      ["fixed-wing aircraft", "こていよくき", "固定翼機", "koteiyokuki"],
      ["rotary-wing aircraft", "かいてんよくき", "回転翼機", "kaitenyokuki"],
      ["tiltrotor aircraft", "ティルトローターき", "ティルトローター機", "tiruto rootaa ki", "noun", "", "tiruto rōtā ki"],
      ["electronic warfare aircraft", "でんしせんき", "電子戦機", "denshisenki"],
      ["government transport aircraft", "せいふせんようき", "政府専用機", "seifu senyouki", "noun", "", "seifu sen'yōki"],
      ["Japan Self-Defense Forces", "じえいたい", "自衛隊", "jieitai"],
      ["Air Self-Defense Force", "こうくうじえいたい", "航空自衛隊", "koukuu jieitai", "noun", "空自", "kōkū jieitai;JASDF"],
      ["Maritime Self-Defense Force", "かいじょうじえいたい", "海上自衛隊", "kaijou jieitai", "noun", "海自", "kaijō jieitai;JMSDF"],
      ["Ground Self-Defense Force", "りくじょうじえいたい", "陸上自衛隊", "rikujou jieitai", "noun", "陸自", "rikujō jieitai;JGSDF"],
      ["aircraft", "こうくうき", "航空機", "koukuuki", "noun", "", "kōkūki"],
      ["unit", "ぶたい", "部隊", "butai"],
      ["squadron", "ひこうたい", "飛行隊", "hikoutai", "noun", "", "hikōtai"],
      ["aircrew", "とうじょういん", "搭乗員", "toujouin", "noun", "", "tōjōin"],
      ["maintenance crew", "せいびいん", "整備員", "seibiin"],

      ["fuselage", "どうたい", "胴体", "doutai", "noun", "", "dōtai"],
      ["aircraft nose", "きしゅ", "機首", "kishu"],
      ["cockpit", "そうじゅうせき", "操縦席", "soujuuseki", "noun", "コックピット", "sōjūseki"],
      ["canopy", "キャノピー", "キャノピー", "kyanopii", "noun", "", "kyanopī"],
      ["main wing", "しゅよく", "主翼", "shuyoku"],
      ["wingtip", "よくたん", "翼端", "yokutan"],
      ["tail section", "びぶ", "尾部", "bibu"],
      ["vertical stabilizer", "すいちょくびよく", "垂直尾翼", "suichoku biyoku", "noun", "", "suichoku biyoku"],
      ["horizontal stabilizer", "すいへいびよく", "水平尾翼", "suihei biyoku"],
      ["pitch-control elevator", "しょうこうだ", "昇降舵", "shoukouda", "noun", "", "shōkōda"],
      ["rudder", "ほうこうだ", "方向舵", "houkouda", "noun", "", "hōkōda"],
      ["aileron", "ほじょよく", "補助翼", "hojoyoku"],
      ["flap", "フラップ", "フラップ", "furappu"],
      ["leading-edge slat", "ぜんえんスラット", "前縁スラット", "zen'en suratto"],
      ["air brake", "エアブレーキ", "エアブレーキ", "ea bureeki", "noun", "", "ea burēki"],
      ["landing gear", "こうちゃくそうち", "降着装置", "kouchaku souchi", "noun", "", "kōchaku sōchi"],
      ["nose gear", "ぜんきゃく", "前脚", "zenkyaku"],
      ["main gear", "しゅきゃく", "主脚", "shukyaku"],
      ["engine", "エンジン", "エンジン", "enjin"],
      ["jet engine", "ジェットエンジン", "ジェットエンジン", "jetto enjin"],
      ["propeller", "プロペラ", "プロペラ", "puropera"],
      ["rotor blade", "ローターブレード", "ローターブレード", "rootaa bureedo", "noun", "", "rōtā burēdo"],
      ["tail rotor", "テールローター", "テールローター", "teeru rootaa", "noun", "", "tēru rōtā"],
      ["air intake", "くうきとりいれぐち", "空気取入口", "kuuki toriireguchi", "noun", "", "kūki toriireguchi"],
      ["exhaust nozzle", "はいきノズル", "排気ノズル", "haiki nozuru"],
      ["afterburner", "アフターバーナー", "アフターバーナー", "afutaa baanaa", "noun", "", "afutā bānā"],
      ["radar", "レーダー", "レーダー", "reedaa", "noun", "", "rēdā"],
      ["radome", "レドーム", "レドーム", "redoomu", "noun", "", "redōmu"],
      ["pitot tube", "ピトーかん", "ピトー管", "pitoo kan", "noun", "", "pitō kan"],
      ["external fuel tank", "ぞうそう", "増槽", "zousou", "noun", "", "zōsō"],
      ["cargo ramp", "かもつランプ", "貨物ランプ", "kamotsu ranpu"],
      ["antenna", "アンテナ", "アンテナ", "antena"],
      ["sensor pod", "センサーポッド", "センサーポッド", "sensaa poddo", "noun", "", "sensā poddo"],
      ["weapon pylon", "ぶそうパイロン", "武装パイロン", "busou pairon", "noun", "", "busō pairon"],
      ["ejection seat", "しゃしゅつざせき", "射出座席", "shashutsu zaseki"],
      ["rescue hoist", "きゅうじょようホイスト", "救助用ホイスト", "kyuujoyou hoisuto", "noun", "", "kyūjoyō hoisuto"],

      ["F-35A Lightning II", "エフさんじゅうごエー ライトニングツー", "F-35A ライトニングII", "efu sanjuugo ee raitoningu tsuu", "noun", "F-35A;F35A", "F-35A;F35A;lightning ii"],
      ["F-15J Eagle", "エフじゅうごジェイ イーグル", "F-15J イーグル", "efu juugo jei iiguru", "noun", "F-15J;F15J", "F-15J;F15J;eagle"],
      ["F-15DJ Eagle", "エフじゅうごディージェイ イーグル", "F-15DJ イーグル", "efu juugo dii jei iiguru", "noun", "F-15DJ;F15DJ", "F-15DJ;F15DJ;eagle"],
      ["F-2A", "エフツーエー", "F-2A", "efu tsuu ee", "noun", "F2A", "F-2A;F2A"],
      ["F-2B", "エフツービー", "F-2B", "efu tsuu bii", "noun", "F2B", "F-2B;F2B"],
      ["C-2 transport", "シーツーゆそうき", "C-2 輸送機", "shii tsuu yusouki", "noun", "C-2;C2", "C-2;C2;shī tsū yusōki"],
      ["C-130H Hercules", "シーひゃくさんじゅうエイチ ハーキュリーズ", "C-130H ハーキュリーズ", "shii hyakusanjuu eichi haakyuriizu", "noun", "C-130H;C130H", "C-130H;C130H;hercules"],
      ["KC-767 tanker", "ケーシーななろくなな くうちゅうきゅうゆき", "KC-767 空中給油機", "kee shii nanarokunana kuuchuu kyuuyuki", "noun", "KC-767;KC767", "KC-767;KC767"],
      ["KC-46A Pegasus", "ケーシーよんじゅうろくエー ペガサス", "KC-46A ペガサス", "kee shii yonjuuroku ee pegasasu", "noun", "KC-46A;KC46A", "KC-46A;KC46A;pegasus"],
      ["E-767 AWACS", "イーななろくなな そうきけいかいかんせいき", "E-767 早期警戒管制機", "ii nanarokunana souki keikai kanseiki", "noun", "E-767;E767", "E-767;E767;AWACS"],
      ["E-2C Hawkeye", "イーツーシー ホークアイ", "E-2C ホークアイ", "ii tsuu shii hookuai", "noun", "E-2C;E2C", "E-2C;E2C;hawkeye"],
      ["RQ-4B Global Hawk", "アールキューよんビー グローバルホーク", "RQ-4B グローバルホーク", "aaru kyuu yon bii guroobaru hooku", "noun", "RQ-4B;RQ4B", "RQ-4B;RQ4B;global hawk"],
      ["U-125A rescue aircraft", "ユーひゃくにじゅうごエー きゅうなんき", "U-125A 救難機", "yuu hyakunijuugo ee kyuunanki", "noun", "U-125A;U125A", "U-125A;U125A"],
      ["UH-60J rescue helicopter", "ユーエイチろくじゅうジェイ きゅうなんヘリコプター", "UH-60J 救難ヘリコプター", "yuu eichi rokujuu jei kyuunan herikoputaa", "noun", "UH-60J;UH60J", "UH-60J;UH60J"],
      ["T-4 trainer", "ティーよん れんしゅうき", "T-4 練習機", "tii yon renshuuki", "noun", "T-4;T4", "T-4;T4"],
      ["T-7 trainer", "ティーなな れんしゅうき", "T-7 練習機", "tii nana renshuuki", "noun", "T-7;T7", "T-7;T7"],
      ["P-1 patrol aircraft", "ピーいち しょうかいき", "P-1 哨戒機", "pii ichi shoukaiki", "noun", "P-1;P1", "P-1;P1"],
      ["P-3C Orion", "ピーさんシー オライオン", "P-3C オライオン", "pii san shii oraion", "noun", "P-3C;P3C", "P-3C;P3C;orion"],
      ["US-2 amphibious aircraft", "ユーエスツー すいりくりょうようき", "US-2 水陸両用機", "yuu esu tsuu suiriku ryouyouki", "noun", "US-2;US2", "US-2;US2"],
      ["SH-60K patrol helicopter", "エスエイチろくじゅうケー しょうかいヘリコプター", "SH-60K 哨戒ヘリコプター", "esu eichi rokujuu kee shoukai herikoputaa", "noun", "SH-60K;SH60K", "SH-60K;SH60K"],
      ["MCH-101 minesweeping and transport helicopter", "エムシーエイチいちまるいち そうかい ゆそうヘリコプター", "MCH-101 掃海・輸送ヘリコプター", "emu shii eichi ichi maru ichi soukai yusou herikoputaa", "noun", "MCH-101;MCH101", "MCH-101;MCH101"],
      ["OH-1 Ninja", "オーエイチいち ニンジャ", "OH-1 ニンジャ", "oo eichi ichi ninja", "noun", "OH-1;OH1", "OH-1;OH1;ninja"],
      ["LR-2 Hayabusa", "エルアールツー はやぶさ", "LR-2 はやぶさ", "eru aaru tsuu hayabusa", "noun", "LR-2;LR2", "LR-2;LR2;hayabusa"],
      ["UH-60JA Black Hawk", "ユーエイチろくじゅうジェイエー ブラックホーク", "UH-60JA ブラックホーク", "yuu eichi rokujuu jei ee burakku hooku", "noun", "UH-60JA;UH60JA", "UH-60JA;UH60JA;black hawk"],
      ["CH-47JA Chinook", "シーエイチよんじゅうななジェイエー チヌーク", "CH-47JA チヌーク", "shii eichi yonjuunana jei ee chinuuku", "noun", "CH-47JA;CH47JA", "CH-47JA;CH47JA;chinook"],
      ["AH-1S Cobra", "エーエイチいちエス コブラ", "AH-1S コブラ", "ee eichi ichi esu kobura", "noun", "AH-1S;AH1S", "AH-1S;AH1S;cobra"],
      ["AH-64D Apache", "エーエイチろくじゅうよんディー アパッチ", "AH-64D アパッチ", "ee eichi rokujuuyon dii apacchi", "noun", "AH-64D;AH64D", "AH-64D;AH64D;apache"],
      ["national marking", "こくせきひょうしき", "国籍標識", "kokuseki hyoushiki", "noun", "日の丸", "kokuseki hyōshiki"],
      ["aircraft serial number", "きたいばんごう", "機体番号", "kitai bangou", "noun", "", "kitai bangō"],
      ["special paint scheme", "とくべつとそう", "特別塗装", "tokubetsu tosou", "noun", "", "tokubetsu tosō"],
      ["unit marking", "ぶたいひょうしき", "部隊標識", "butai hyoushiki", "noun", "", "butai hyōshiki"],
      ["B-777 government transport", "ビーセブンセブンセブン せいふせんようき", "B-777 政府専用機", "bii sebun sebun sebun seifu senyouki", "noun", "B-777;B777", "B-777;B777"],
      ["U-4 utility aircraft", "ユーヨン たようとしえんき", "U-4 多用途支援機", "yuu yon tayouto shienki", "noun", "U-4;U4", "U-4;U4"],
      ["U-680A flight inspection aircraft", "ユーろくはちまるエー ひこうてんけんき", "U-680A 飛行点検機", "yuu roku hachi maru ee hikou tenkenki", "noun", "U-680A;U680A", "U-680A;U680A"],
      ["T-400 trainer", "ティーよんひゃく れんしゅうき", "T-400 練習機", "tii yonhyaku renshuuki", "noun", "T-400;T400", "T-400;T400"],
      ["TH-135 trainer helicopter", "ティーエイチひゃくさんじゅうご れんしゅうヘリコプター", "TH-135 練習ヘリコプター", "tii eichi hyakusanjuugo renshuu herikoputaa", "noun", "TH-135;TH135", "TH-135;TH135"]
    ),
    slotMeanings: [
      ["military aircraft", "military aircraft"], ["fighter aircraft", "fighter aircraft"],
      ["transport aircraft", "transport aircraft"], ["tanker aircraft", "tanker aircraft"],
      ["airborne early warning aircraft", "airborne early warning aircraft"], ["rescue aircraft", "rescue aircraft"],
      ["helicopter", "helicopters"], ["tiltrotor aircraft", "tiltrotor aircraft"],
      ["Air Self-Defense Force", "the Air Self-Defense Force"], ["Maritime Self-Defense Force", "the Maritime Self-Defense Force"],
      ["fuselage", "aircraft fuselages"], ["aircraft nose", "aircraft noses"], ["cockpit", "cockpit design"],
      ["canopy", "aircraft canopies"], ["main wing", "main wings"], ["vertical stabilizer", "vertical stabilizers"],
      ["landing gear", "landing gear"], ["jet engine", "jet engines"], ["radar", "aircraft radar"], ["radome", "radomes"],
      "F-35A Lightning II", "F-15J Eagle", "F-2A", "C-2 transport", "E-767 AWACS",
      "P-1 patrol aircraft", "US-2 amphibious aircraft", "OH-1 Ninja", "CH-47JA Chinook", "special paint scheme"
    ],
    dialogues: [
      dialogue("aircraft-role", "Identifying an aircraft type", "Beside a static display", [
        ["traveler", "What kind of aircraft is this?", "この航空機は何の種類ですか。", "これ、何の種類の航空機？"],
        ["local", "It is a C-2 transport aircraft.", "C-2輸送機です。", "C-2輸送機だよ。"],
        ["traveler", "Which service operates it?", "どの自衛隊が運用していますか。", "どの自衛隊が運用してる？"],
        ["local", "The Air Self-Defense Force operates it.", "航空自衛隊が運用しています。", "航空自衛隊が運用してるよ。"]
      ]),
      dialogue("aircraft-parts", "Asking about an aircraft part", "Looking at an aircraft diagram", [
        ["traveler", "What is the round part above the fuselage?", "機体上部の丸い部分は何ですか。", "機体の上の丸い部分は何？"],
        ["local", "It is the radome that covers the radar.", "レーダーを覆うレドームです。", "レーダーを覆うレドームだよ。"],
        ["traveler", "Are the parts behind the main wing the flaps?", "主翼の後ろにある部分はフラップですか。", "主翼の後ろにあるのはフラップ？"],
        ["local", "Yes. They increase lift during takeoff and landing.", "はい。離着陸時に揚力を増やします。", "うん。離着陸のときに揚力を増やすよ。"]
      ]),
      dialogue("aircraft-recognition", "Recognizing a Japanese aircraft", "At the edge of a viewing area", [
        ["traveler", "Is that an F-15J?", "あれはF-15Jですか。", "あれ、F-15J？"],
        ["local", "Yes. The unit marking is on the tail.", "はい。尾翼に部隊標識があります。", "うん。尾翼に部隊標識があるよ。"],
        ["traveler", "May I photograph this special paint scheme?", "この特別塗装機を撮影してもいいですか。", "この特別塗装機、撮ってもいい？"],
        ["local", "Yes, you can photograph it from the viewing area.", "はい、観覧エリアから撮影できます。", "うん、観覧エリアから撮れるよ。"]
      ])
    ],
    sentence: {
      english: "I am interested in {meaning}.",
      formal: "{term}に興味があります",
      informal: "{term}に興味がある"
    },
    response: {
      promptFormal: "{term}に興味がありますか",
      promptInformal: "{term}に興味がある？",
      answerFormal: "はい、{term}に興味があります",
      answerInformal: "うん、{term}に興味がある"
    }
  },
  {
    id: "air-bases-shows-jsdf",
    title: "Air Shows & Base Visits",
    shortTitle: "Air Shows",
    description: "Navigate public base events, flying displays, announcements, facilities, and visitor safety.",
    category: "interests",
    domain: raw(
      ["air base", "こうくうきち", "航空基地", "koukuu kichi", "noun", "", "kōkū kichi"],
      ["base entrance", "きちいりぐち", "基地入口", "kichi iriguchi"],
      ["main gate", "せいもん", "正門", "seimon"],
      ["visitor entrance", "らいじょうしゃいりぐち", "来場者入口", "raijousha iriguchi", "noun", "", "raijōsha iriguchi"],
      ["security checkpoint", "ほあんけんさじょ", "保安検査所", "hoan kensajo"],
      ["identification", "みぶんしょうめいしょ", "身分証明書", "mibun shoumeisho", "noun", "", "mibun shōmeisho"],
      ["bag inspection", "てにもつけんさ", "手荷物検査", "tenimotsu kensa"],
      ["restricted area", "たちいりきんしくいき", "立入禁止区域", "tachiiri kinshi kuiki"],
      ["runway", "かっそうろ", "滑走路", "kassouro", "noun", "", "kassōro"],
      ["taxiway", "ゆうどうろ", "誘導路", "yuudouro", "noun", "", "yūdōro"],
      ["hangar", "かくのうこ", "格納庫", "kakunouko", "noun", "", "kakunōko"],
      ["apron", "エプロン", "エプロン", "epuron"],
      ["flight line", "ひこうせん", "飛行線", "hikousen", "noun", "", "hikōsen"],
      ["control tower", "かんせいとう", "管制塔", "kanseitou", "noun", "", "kanseitō"],
      ["admission ticket", "にゅうじょうけん", "入場券", "nyuujouken", "noun", "", "nyūjōken"],
      ["advance admission reservation", "じぜんにゅうじょうよやく", "事前入場予約", "jizen nyuujou yoyaku", "noun", "", "jizen nyūjō yoyaku"],
      ["opening time", "かいじょうじこく", "開場時刻", "kaijou jikoku", "noun", "", "kaijō jikoku"],
      ["entry deadline", "にゅうじょうしめきりじこく", "入場締切時刻", "nyuujou shimekiri jikoku", "noun", "", "nyūjō shimekiri jikoku"],
      ["event staff", "イベントかかりいん", "イベント係員", "ibento kakariin"],
      ["information booth", "あんないじょ", "案内所", "annaijo"],
      ["souvenir stand", "グッズうりば", "グッズ売り場", "guzzu uriba"],
      ["food stall", "いんしょくブース", "飲食ブース", "inshoku buusu", "noun", "", "inshoku būsu"],
      ["portable toilet", "かせつトイレ", "仮設トイレ", "kasetsu toire"],
      ["rest area", "きゅうけいじょ", "休憩所", "kyuukeijo", "noun", "", "kyūkeijo"],
      ["barrier fence", "きせいさく", "規制柵", "kiseisaku"],
      ["spectator route", "かんらんけいろ", "観覧経路", "kanran keiro"],
      ["one-way pedestrian route", "いっぽうつうこうけいろ", "一方通行経路", "ippou tsuukou keiro", "noun", "", "ippō tsūkō keiro"],
      ["queue cutoff", "れつしめきり", "列締切", "retsu shimekiri"],
      ["emergency announcement", "きんきゅうほうそう", "緊急放送", "kinkyuu housou", "noun", "", "kinkyū hōsō"],
      ["static display", "ちじょうてんじ", "地上展示", "chijou tenji", "noun", "", "chijō tenji"],
      ["flight demonstration", "ひこうてんじ", "飛行展示", "hikou tenji", "noun", "", "hikō tenji"],
      ["aerobatic team", "きょくぎひこうたい", "曲技飛行隊", "kyokugi hikoutai", "noun", "", "kyokugi hikōtai"],
      ["Blue Impulse", "ブルーインパルス", "ブルーインパルス", "buruu inparusu", "noun", "", "burū inparusu"],
      ["air show", "こうくうさい", "航空祭", "koukuusai", "noun", "", "kōkūsai"],
      ["open base day", "きちかいほうび", "基地開放日", "kichi kaihoubi", "noun", "", "kichi kaihōbi"],
      ["event program", "イベントプログラム", "イベントプログラム", "ibento puroguramu"],
      ["venue map", "かいじょうあんないず", "会場案内図", "kaijou annaizu", "noun", "", "kaijō annaizu"],
      ["viewing area", "かんらんエリア", "観覧エリア", "kanran eria"],
      ["photography area", "さつえいエリア", "撮影エリア", "satsuei eria"],
      ["paid viewing area", "ゆうりょうかんらんせき", "有料観覧席", "yuuryou kanranseki", "noun", "", "yūryō kanranseki"],
      ["crowd", "こんざつ", "混雑", "konzatsu"],
      ["announcement", "じょうないほうそう", "場内放送", "jounai housou", "noun", "", "jōnai hōsō"],
      ["flight schedule", "ひこうよてい", "飛行予定", "hikou yotei", "noun", "", "hikō yotei"],
      ["takeoff", "りりく", "離陸", "ririku"],
      ["landing", "ちゃくりく", "着陸", "chakuriku"],
      ["flypast", "じょうくうつうか", "上空通過", "joukuu tsuuka", "noun", "", "jōkū tsūka"],
      ["formation flight", "へんたいひこう", "編隊飛行", "hentai hikou", "noun", "", "hentai hikō"],
      ["smoke trail", "カラースモーク", "カラースモーク", "karaa sumooku", "noun", "", "karā sumōku"],
      ["engine noise", "エンジンおん", "エンジン音", "enjin on"],
      ["hearing protection", "みみせん", "耳栓", "mimisen"],
      ["sunshade", "ひよけ", "日よけ", "hiyoke"],
      ["water station", "きゅうすいじょ", "給水所", "kyuusuijo", "noun", "", "kyūsuijo"],
      ["first-aid station", "きゅうごしょ", "救護所", "kyuugosho", "noun", "", "kyūgosho"],
      ["lost child center", "まいごセンター", "迷子センター", "maigo sentaa", "noun", "", "maigo sentā"],
      ["emergency exit", "ひじょうぐち", "非常口", "hijouguchi", "noun", "", "hijōguchi"],
      ["shuttle bus", "シャトルバス", "シャトルバス", "shatoru basu"],
      ["parking lot", "ちゅうしゃじょう", "駐車場", "chuushajou", "noun", "", "chūshajō"],
      ["prohibited item", "もちこみきんしひん", "持込禁止品", "mochikomi kinshihin"],
      ["event cancellation", "イベントちゅうし", "イベント中止", "ibento chuushi", "noun", "", "ibento chūshi"],
      ["weather decision", "てんこうはんだん", "天候判断", "tenkou handan", "noun", "", "tenkō handan"],
      ["step ladder", "きゃたつ", "脚立", "kyatatsu"],
      ["monopod", "いっきゃく", "一脚", "ikkyaku"],
      ["selfie stick", "じどりぼう", "自撮り棒", "jidoribou", "noun", "", "jidoribō"],
      ["drone", "ドローン", "ドローン", "doroon", "noun", "", "dorōn"],
      ["radio", "むせんき", "無線機", "musenki"],
      ["metal detector screening", "きんぞくたんちけんさ", "金属探知検査", "kinzoku tanchi kensa"],
      ["body check", "ボディチェック", "ボディチェック", "bodi chekku"],
      ["temporary baggage storage", "てにもついちじあずかり", "手荷物一時預かり", "tenimotsu ichiji azukari"],
      ["staff instructions", "かかりいんのしじ", "係員の指示", "kakariin no shiji"],
      ["entry queue", "にゅうじょうたいきれつ", "入場待機列", "nyuujou taikiretsu", "noun", "", "nyūjō taikiretsu"],
      ["re-entry", "さいにゅうじょう", "再入場", "sainyuujou", "noun", "", "sainyūjō"],
      ["shuttle bus stop", "シャトルバスのりば", "シャトルバス乗り場", "shatoru basu noriba"],
      ["public transport", "こうきょうこうつうきかん", "公共交通機関", "koukyou koutsuu kikan", "noun", "", "kōkyō kōtsū kikan"],
      ["flight cancellation", "ひこうちゅうし", "飛行中止", "hikou chuushi", "noun", "", "hikō chūshi"],
      ["program change", "プログラムへんこう", "プログラム変更", "puroguramu henkou", "noun", "", "puroguramu henkō"],
      ["aircraft towing", "こうくうきけんいん", "航空機牽引", "koukuuki kenin", "noun", "", "kōkūki ken'in"],
      ["engine start", "エンジンしどう", "エンジン始動", "enjin shidou", "noun", "", "enjin shidō"],
      ["roped-off area", "きせいせん", "規制線", "kiseisen"],
      ["heat haze", "かげろう", "陽炎", "kagerou", "noun", "かげろう", "kagerō"],
      ["ear defenders", "イヤーマフ", "イヤーマフ", "iyaa mafu", "noun", "", "iyā mafu"]
    ),
    slotMeanings: [
      "base entrance", "main gate", "visitor entrance", "security checkpoint", "restricted area", "runway", "taxiway",
      "hangar", "apron", "control tower", "static display", "venue map", "viewing area", "photography area",
      "paid viewing area", "water station", "first-aid station", "lost child center", "emergency exit", "shuttle bus",
      "parking lot", "temporary baggage storage", "entry queue", "shuttle bus stop", "roped-off area"
    ],
    dialogues: [
      dialogue("airshow-entry", "Entering the event", "At the visitor gate", [
        ["traveler", "Is this the visitor entrance?", "こちらは来場者入口ですか。", "ここ、来場者入口？"],
        ["local", "Yes. Please open your bag for inspection.", "はい。手荷物検査のため、かばんを開けてください。", "うん。手荷物検査で、かばんを開けて。"],
        ["traveler", "Are tripods allowed?", "三脚は持ち込めますか。", "三脚は持ち込める？"],
        ["local", "Tripods are prohibited at this event.", "この航空祭では三脚の持ち込みは禁止です。", "この航空祭では三脚は持ち込めないよ。"]
      ]),
      dialogue("airshow-schedule", "Checking the program", "Near the viewing area", [
        ["traveler", "When does Blue Impulse fly?", "ブルーインパルスは何時に飛びますか。", "ブルーインパルスは何時に飛ぶ？"],
        ["local", "The demonstration starts at one.", "飛行展示は1時に始まります。", "飛行展示は1時に始まるよ。"],
        ["traveler", "Where is the best viewing area?", "見やすい観覧エリアはどこですか。", "見やすい観覧エリアはどこ？"],
        ["local", "The north side is less crowded.", "北側は比較的空いています。", "北側はわりと空いてる。"]
      ]),
      dialogue("airshow-safety", "Following safety guidance", "During a busy event", [
        ["local", "The engine noise will be very loud.", "エンジン音が非常に大きくなります。", "エンジン音がすごく大きくなるよ。"],
        ["traveler", "Where can I buy earplugs?", "耳栓はどこで買えますか。", "耳栓はどこで買える？"],
        ["local", "They are sold at the event shop.", "会場の売店で販売しています。", "会場の売店で売ってる。"],
        ["traveler", "Thank you. Is there a water station?", "ありがとうございます。給水所はありますか。", "ありがとう。給水所はある？"],
        ["local", "Yes, there is one in the central plaza.", "はい、中央広場にあります。", "うん、中央広場にあるよ。"]
      ])
    ],
    sentence: { english: "Where is the {meaning}?", formal: "{term}はどこですか", informal: "{term}はどこ？" },
    response: {
      promptFormal: "{term}を探していますか",
      promptInformal: "{term}を探してる？",
      answerFormal: "はい、{term}を探しています",
      answerInformal: "うん、{term}を探してる"
    }
  },
  {
    id: "numbers-dates-time",
    title: "Numbers, Dates & Time",
    shortTitle: "Time & Numbers",
    description: "Handle prices, dates, times, quantities, counters, and schedules.",
    category: "essentials",
    domain: raw(
      ["zero", "れい", "零", "rei", "counter", "ゼロ"],
      ["one", "いち", "一", "ichi", "counter"],
      ["two", "に", "二", "ni", "counter"],
      ["three", "さん", "三", "san", "counter"],
      ["four", "よん", "四", "yon", "counter", "し", "shi"],
      ["five", "ご", "五", "go", "counter"],
      ["six", "ろく", "六", "roku", "counter"],
      ["seven", "なな", "七", "nana", "counter", "しち", "shichi"],
      ["eight", "はち", "八", "hachi", "counter"],
      ["nine", "きゅう", "九", "kyuu", "counter", "く", "kyū"],
      ["ten", "じゅう", "十", "juu", "counter", "", "jū"],
      ["hundred", "ひゃく", "百", "hyaku", "counter"],
      ["thousand", "せん", "千", "sen", "counter"],
      ["ten thousand", "いちまん", "一万", "ichiman", "counter"],
      ["number", "すうじ", "数字", "suuji", "noun", "", "sūji"],
      ["quantity", "すうりょう", "数量", "suuryou", "noun", "", "sūryō"],
      ["time", "じかん", "時間", "jikan"],
      ["hour", "じ", "時", "ji", "counter"],
      ["minute", "ふん", "分", "fun", "counter", "ぷん", "pun"],
      ["second", "びょう", "秒", "byou", "counter", "", "byō"],
      ["morning", "ごぜん", "午前", "gozen"],
      ["afternoon", "ごご", "午後", "gogo"],
      ["noon", "しょうご", "正午", "shougo", "noun", "", "shōgo"],
      ["midnight", "まよなか", "真夜中", "mayonaka"],
      ["date", "ひづけ", "日付", "hizuke"],
      ["day", "ひ", "日", "hi"],
      ["week", "しゅう", "週", "shuu", "counter", "", "shū"],
      ["month", "つき", "月", "tsuki"],
      ["year", "とし", "年", "toshi"],
      ["calendar", "カレンダー", "カレンダー", "karendaa", "noun", "", "karendā"],
      ["Monday", "げつようび", "月曜日", "getsuyoubi", "noun", "", "getsuyōbi"],
      ["Tuesday", "かようび", "火曜日", "kayoubi", "noun", "", "kayōbi"],
      ["Wednesday", "すいようび", "水曜日", "suiyoubi", "noun", "", "suiyōbi"],
      ["Thursday", "もくようび", "木曜日", "mokuyoubi", "noun", "", "mokuyōbi"],
      ["Friday", "きんようび", "金曜日", "kinyoubi", "noun", "", "kinyōbi"],
      ["Saturday", "どようび", "土曜日", "doyoubi", "noun", "", "doyōbi"],
      ["Sunday", "にちようび", "日曜日", "nichiyoubi", "noun", "", "nichiyōbi"],
      ["January", "いちがつ", "一月", "ichigatsu"],
      ["February", "にがつ", "二月", "nigatsu"],
      ["March", "さんがつ", "三月", "sangatsu"],
      ["April", "しがつ", "四月", "shigatsu"],
      ["May", "ごがつ", "五月", "gogatsu"],
      ["June", "ろくがつ", "六月", "rokugatsu"],
      ["July", "しちがつ", "七月", "shichigatsu"],
      ["August", "はちがつ", "八月", "hachigatsu"],
      ["September", "くがつ", "九月", "kugatsu"],
      ["October", "じゅうがつ", "十月", "juugatsu", "noun", "", "jūgatsu"],
      ["November", "じゅういちがつ", "十一月", "juuichigatsu", "noun", "", "jūichigatsu"],
      ["December", "じゅうにがつ", "十二月", "juunigatsu", "noun", "", "jūnigatsu"],
      ["today", "きょう", "今日", "kyou", "noun", "", "kyō"],
      ["tomorrow", "あした", "明日", "ashita"],
      ["yesterday", "きのう", "昨日", "kinou", "noun", "", "kinō"],
      ["this week", "こんしゅう", "今週", "konshuu", "noun", "", "konshū"],
      ["next week", "らいしゅう", "来週", "raishuu", "noun", "", "raishū"],
      ["last week", "せんしゅう", "先週", "senshuu", "noun", "", "senshū"],
      ["early", "はやい", "早い", "hayai", "adjective"],
      ["late", "おそい", "遅い", "osoi", "adjective"],
      ["half past", "はん", "半", "han", "counter"],
      ["about", "ごろ", "頃", "goro", "phrase"],
      ["duration", "しょようじかん", "所要時間", "shoyou jikan", "noun", "", "shoyō jikan"],
      ["yen", "えん", "円", "en", "counter"],
      ["people counter", "にん", "", "nin", "counter", "人;り;ひとり;ふたり"],
      ["item counter", "こ", "個", "ko", "counter"],
      ["flat-object counter", "まい", "枚", "mai", "counter"],
      ["long-object counter", "ほん", "本", "hon", "counter", "ぼん;ぽん", "bon;pon"],
      ["machine counter", "だい", "台", "dai", "counter"],
      ["floor counter", "かい", "階", "kai", "counter", "がい", "gai"],
      ["night counter", "はく", "泊", "haku", "counter", "ぱく", "paku"],
      ["day counter", "にち", "", "nichi", "counter", "日;か", "ka"],
      ["age counter", "さい", "歳", "sai", "counter", "才"],
      ["first day", "ついたち", "一日", "tsuitachi", "counter"],
      ["second day", "ふつか", "二日", "futsuka", "counter"],
      ["third day", "みっか", "三日", "mikka", "counter"],
      ["fourth day", "よっか", "四日", "yokka", "counter"],
      ["fifth day", "いつか", "五日", "itsuka", "counter"],
      ["sixth day", "むいか", "六日", "muika", "counter"],
      ["seventh day", "なのか", "七日", "nanoka", "counter"],
      ["eighth day", "ようか", "八日", "youka", "counter", "", "yōka"],
      ["ninth day", "ここのか", "九日", "kokonoka", "counter"],
      ["tenth day", "とおか", "十日", "tooka", "counter", "", "tōka"],
      ["twentieth day", "はつか", "二十日", "hatsuka", "counter"],
      ["twenty-fourth day", "にじゅうよっか", "二十四日", "nijuuyokka", "counter", "", "nijūyokka"],
      ["one person", "ひとり", "一人", "hitori", "counter"],
      ["two people", "ふたり", "二人", "futari", "counter"],
      ["one item", "ひとつ", "一つ", "hitotsu", "counter"]
    ),
    slotMeanings: [
      "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December",
      "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "today", "tomorrow", "yesterday", "noon", "midnight"
    ],
    dialogues: [
      dialogue("time-appointment", "Confirming a time", "Making a booking", [
        ["local", "What time would you like?", "何時をご希望ですか。", "何時がいい？"],
        ["traveler", "Three thirty, please.", "3時半をお願いします。", "3時半でお願い。"],
        ["local", "Is August ninth correct?", "8月9日でよろしいですか。", "8月9日でいい？"],
        ["traveler", "Yes, that is correct.", "はい、間違いありません。", "うん、それで合ってる。"]
      ]),
      dialogue("time-duration", "Asking how long", "Planning a journey", [
        ["traveler", "How long does it take?", "所要時間はどのくらいですか。", "どのくらいかかる？"],
        ["local", "About one hour and twenty minutes.", "1時間20分くらいです。", "1時間20分くらい。"],
        ["traveler", "What time is the last train?", "終電は何時ですか。", "終電は何時？"],
        ["local", "It leaves at eleven forty-two.", "11時42分発です。", "11時42分発。"]
      ]),
      dialogue("time-quantity", "Confirming quantity", "At a counter", [
        ["local", "How many do you need?", "いくつ必要ですか。", "いくつ必要？"],
        ["traveler", "Three, please.", "3つお願いします。", "3つお願い。"],
        ["local", "The total is 1,800 yen.", "合計1,800円です。", "合計1,800円。"],
        ["traveler", "Here is 2,000 yen.", "2,000円でお願いします。", "2,000円でお願い。"]
      ])
    ],
    sentence: {
      english: "Is {meaning} correct?",
      formal: "{term}で合っていますか",
      informal: "{term}で合ってる？"
    },
    response: {
      promptFormal: "{term}でよろしいですか",
      promptInformal: "{term}でいい？",
      answerFormal: "はい、{term}でお願いします",
      answerInformal: "うん、{term}でお願い"
    }
  },
  {
    id: "directions-navigation",
    title: "Directions & Navigation",
    shortTitle: "Directions",
    description: "Ask where things are, understand landmarks, and recover when lost.",
    category: "essentials",
    domain: raw(
      ["station exit", "えきのでぐち", "駅の出口", "eki no deguchi"],
      ["intersection", "こうさてん", "交差点", "kousaten", "noun", "", "kōsaten"],
      ["traffic light", "しんごう", "信号", "shingou", "noun", "", "shingō"],
      ["crosswalk", "おうだんほどう", "横断歩道", "oudan hodou", "noun", "", "ōdan hodō"],
      ["road", "みち", "道", "michi"],
      ["main street", "おおどおり", "大通り", "oodoori", "noun", "", "ōdōri"],
      ["alley", "ろじ", "路地", "roji"],
      ["bridge", "はし", "橋", "hashi"],
      ["tunnel", "トンネル", "トンネル", "tonneru"],
      ["corner", "かど", "角", "kado"],
      ["block", "くかく", "区画", "kukaku"],
      ["building", "たてもの", "建物", "tatemono"],
      ["landmark", "めじるし", "目印", "mejirushi"],
      ["map", "ちず", "地図", "chizu"],
      ["address", "じゅうしょ", "住所", "juusho", "noun", "", "jūsho"],
      ["north", "きた", "北", "kita"],
      ["south", "みなみ", "南", "minami"],
      ["east", "ひがし", "東", "higashi"],
      ["west", "にし", "西", "nishi"],
      ["front", "まえ", "前", "mae"],
      ["back", "うしろ", "後ろ", "ushiro"],
      ["inside", "なか", "中", "naka"],
      ["outside", "そと", "外", "soto"],
      ["upstairs", "うえのかい", "上の階", "ue no kai"],
      ["downstairs", "したのかい", "下の階", "shita no kai"],
      ["elevator", "エレベーター", "エレベーター", "erebeetaa", "noun", "", "erebētā"],
      ["stairs", "かいだん", "階段", "kaidan"],
      ["bus stop", "バスてい", "バス停", "basutei"],
      ["taxi stand", "タクシーのりば", "タクシー乗り場", "takushii noriba", "noun", "", "takushī noriba"],
      ["tourist information", "かんこうあんないじょ", "観光案内所", "kankou annaijo", "noun", "", "kankō annaijo"],
      ["restroom", "トイレ", "トイレ", "toire"],
      ["convenience store", "コンビニ", "コンビニ", "konbini"],
      ["bank", "ぎんこう", "銀行", "ginkou", "noun", "", "ginkō"],
      ["post office", "ゆうびんきょく", "郵便局", "yuubinkyoku", "noun", "", "yūbinkyoku"],
      ["police box", "こうばん", "交番", "kouban", "noun", "", "kōban"],
      ["hotel", "ホテル", "ホテル", "hoteru"],
      ["restaurant", "レストラン", "レストラン", "resutoran"],
      ["park", "こうえん", "公園", "kouen", "noun", "", "kōen"],
      ["temple", "おてら", "お寺", "otera"],
      ["shrine", "じんじゃ", "神社", "jinja"],
      ["museum", "はくぶつかん", "博物館", "hakubutsukan"],
      ["shopping street", "しょうてんがい", "商店街", "shoutengai", "noun", "", "shōtengai"],
      ["next to", "となり", "隣", "tonari", "adverb"],
      ["across from", "むかい", "向かい", "mukai", "adverb"],
      ["between", "あいだ", "間", "aida", "adverb"],
      ["nearby", "ちかく", "近く", "chikaku", "adverb"],
      ["far away", "とおく", "遠く", "tooku", "adverb", "", "tōku"],
      ["on foot", "とほ", "徒歩", "toho", "adverb"],
      ["turn right", "みぎにまがる", "右に曲がる", "migi ni magaru", "phrase"],
      ["turn left", "ひだりにまがる", "左に曲がる", "hidari ni magaru", "phrase"],
      ["go straight", "まっすぐすすむ", "まっすぐ進む", "massugu susumu", "phrase"],
      ["cross", "わたる", "渡る", "wataru", "verb"],
      ["continue", "すすむ", "進む", "susumu", "verb"],
      ["go back", "もどる", "戻る", "modoru", "verb"],
      ["get lost", "みちにまよう", "道に迷う", "michi ni mayou", "phrase", "", "michi ni mayō"],
      ["route", "けいろ", "経路", "keiro"],
      ["shortcut", "ちかみち", "近道", "chikamichi"],
      ["destination", "もくてきち", "目的地", "mokutekichi"],
      ["current location", "げんざいち", "現在地", "genzaichi"],
      ["direction", "ほうこう", "方向", "houkou", "noun", "", "hōkō"],
      ["station rotary", "えきまえロータリー", "駅前ロータリー", "ekimae rootarii", "noun", "", "ekimae rōtarī"],
      ["pedestrian bridge", "ほどうきょう", "歩道橋", "hodoukyou", "noun", "", "hodōkyō"],
      ["underground passage", "ちかどう", "地下道", "chikadou", "noun", "", "chikadō"],
      ["overpass", "りっきょう", "陸橋", "rikkyou", "noun", "", "rikkyō"],
      ["slope", "さか", "坂", "saka"],
      ["steep hill", "きゅうなさか", "急な坂", "kyuu na saka", "noun", "", "kyū na saka"],
      ["dead end", "いきどまり", "行き止まり", "ikidomari"],
      ["one-way street", "いっぽうつうこう", "一方通行", "ippou tsuukou", "noun", "", "ippō tsūkō"],
      ["gate", "もん", "門", "mon"],
      ["north side", "きたがわ", "北側", "kitagawa"],
      ["south side", "みなみがわ", "南側", "minamigawa"],
      ["ground floor", "いっかい", "一階", "ikkai", "noun", "1階"],
      ["basement", "ちか", "地下", "chika"],
      ["walking time", "とほじかん", "徒歩時間", "toho jikan"],
      ["walking route", "とほルート", "徒歩ルート", "toho ruuto", "noun", "", "toho rūto"],
      ["accessible route", "バリアフリールート", "バリアフリールート", "bariafurii ruuto", "noun", "", "bariafurī rūto"],
      ["detour route", "うかいろ", "迂回路", "ukairo"],
      ["GPS", "ジーピーエス", "GPS", "jii pii esu", "noun", "", "jī pī esu"],
      ["map app", "ちずアプリ", "地図アプリ", "chizu apuri"],
      ["share location", "いちじょうほうをきょうゆうする", "位置情報を共有する", "ichi jouhou o kyouyuu suru", "phrase", "", "ichi jōhō o kyōyū suru"],
      ["taxi", "タクシー", "タクシー", "takushii", "noun", "", "takushī"],
      ["taxi driver", "タクシーうんてんしゅ", "タクシー運転手", "takushii untenshu", "noun", "", "takushī untenshu"],
      ["this address, please", "このじゅうしょまでおねがいします", "この住所までお願いします", "kono juusho made onegaishimasu", "phrase", "", "kono jūsho made onegaishimasu"],
      ["ride-hailing app", "はいしゃアプリ", "配車アプリ", "haisha apuri"],
      ["step-free route", "だんさのないけいろ", "段差のない経路", "dansa no nai keiro"]
    ),
    slotMeanings: [
      "station exit", "intersection", "traffic light", "crosswalk", "road", "main street", "alley", "bridge", "tunnel",
      "corner", "block", "building", "landmark", "elevator", "stairs", "bus stop", "taxi stand", "tourist information",
      "restroom", "convenience store", "bank", "post office", "police box", "hotel", "restaurant", "park", "temple",
      "shrine", "museum", "shopping street", "station rotary", "pedestrian bridge", "underground passage", "gate", "basement",
      "taxi", "taxi driver", ["this address, please", "this address"], "ride-hailing app", "step-free route"
    ],
    dialogues: [
      dialogue("directions-station", "Finding an exit", "Inside a station", [
        ["traveler", "Which exit is closest to the museum?", "博物館に一番近い出口はどこですか。", "博物館に一番近い出口はどこ？"],
        ["local", "Use the east exit.", "東口を使ってください。", "東口を使って。"],
        ["traveler", "Is there an elevator?", "エレベーターはありますか。", "エレベーターはある？"],
        ["local", "Yes, beside the ticket gate.", "はい、改札口の隣です。", "うん、改札口の隣。"]
      ]),
      dialogue("directions-walking", "Following directions", "On the street", [
        ["traveler", "How do I get to the shrine?", "神社へはどう行けばいいですか。", "神社へはどう行けばいい？"],
        ["local", "Go straight to the second light.", "2つ目の信号までまっすぐ進んでください。", "2つ目の信号までまっすぐ進んで。"],
        ["traveler", "Then do I turn left?", "それから左に曲がりますか。", "それから左に曲がる？"],
        ["local", "Yes, it is across from the park.", "はい、公園の向かいです。", "うん、公園の向かい。"]
      ]),
      dialogue("directions-lost", "When lost", "Showing a map", [
        ["traveler", "I think I am lost.", "道に迷ったようです。", "道に迷ったみたい。"],
        ["local", "Where do you want to go?", "どこへ行きたいですか。", "どこへ行きたい？"],
        ["traveler", "This address, please.", "この住所へ行きたいです。", "この住所へ行きたい。"],
        ["local", "You are two blocks away.", "ここから2ブロック先です。", "ここから2ブロック先だよ。"]
      ])
    ],
    sentence: { english: "Where is the {meaning}?", formal: "{term}はどこですか", informal: "{term}はどこ？" },
    response: {
      promptFormal: "{term}を探していますか",
      promptInformal: "{term}を探してる？",
      answerFormal: "はい、{term}を探しています",
      answerInformal: "うん、{term}を探してる"
    }
  },
  {
    id: "shopping-payments",
    title: "Shopping & Payments",
    shortTitle: "Shopping",
    description: "Find products, ask about sizes, understand prices, and pay locally.",
    category: "daily",
    domain: raw(
      ["store", "みせ", "店", "mise"],
      ["department store", "デパート", "デパート", "depaato", "noun", "", "depāto"],
      ["convenience store", "コンビニ", "コンビニ", "konbini"],
      ["supermarket", "スーパー", "スーパー", "suupaa", "noun", "", "sūpā"],
      ["drugstore", "ドラッグストア", "ドラッグストア", "doraggu sutoa"],
      ["souvenir shop", "おみやげや", "お土産屋", "omiyageya"],
      ["checkout", "レジ", "レジ", "reji"],
      ["shop clerk", "てんいん", "店員", "tenin"],
      ["product", "しょうひん", "商品", "shouhin", "noun", "", "shōhin"],
      ["price", "ねだん", "値段", "nedan"],
      ["tax", "ぜいきん", "税金", "zeikin"],
      ["tax free", "めんぜい", "免税", "menzei"],
      ["passport", "パスポート", "パスポート", "pasupooto", "noun", "", "pasupōto"],
      ["receipt", "レシート", "レシート", "reshiito", "noun", "", "reshīto"],
      ["shopping bag", "かいものぶくろ", "買い物袋", "kaimono bukuro"],
      ["gift wrapping", "ラッピング", "ラッピング", "rappingu"],
      ["size", "サイズ", "サイズ", "saizu"],
      ["color", "いろ", "色", "iro"],
      ["stock", "ざいこ", "在庫", "zaiko"],
      ["fitting room", "しちゃくしつ", "試着室", "shichakushitsu"],
      ["sample", "みほん", "見本", "mihon"],
      ["warranty", "ほしょう", "保証", "hoshou", "noun", "", "hoshō"],
      ["return", "へんぴん", "返品", "henpin"],
      ["exchange", "こうかん", "交換", "koukan", "noun", "", "kōkan"],
      ["payment", "しはらい", "支払い", "shiharai"],
      ["cash", "げんきん", "現金", "genkin"],
      ["credit card", "クレジットカード", "クレジットカード", "kurejitto kaado", "noun", "", "kurejitto kādo"],
      ["IC payment", "アイシーけっさい", "IC決済", "aishii kessai", "noun", "", "aishī kessai"],
      ["QR payment", "キューアールけっさい", "QR決済", "kyuu aaru kessai", "noun", "", "kyū āru kessai"],
      ["PIN", "あんしょうばんごう", "暗証番号", "anshou bangou", "noun", "", "anshō bangō"],
      ["signature", "サイン", "サイン", "sain"],
      ["coin", "こうか", "硬貨", "kouka", "noun", "", "kōka"],
      ["banknote", "しへい", "紙幣", "shihei"],
      ["change", "おつり", "お釣り", "otsuri"],
      ["discount", "わりびき", "割引", "waribiki"],
      ["sale", "セール", "セール", "seeru", "noun", "", "sēru"],
      ["coupon", "クーポン", "クーポン", "kuupon", "noun", "", "kūpon"],
      ["point card", "ポイントカード", "ポイントカード", "pointo kaado", "noun", "", "pointo kādo"],
      ["total", "ごうけい", "合計", "goukei", "noun", "", "gōkei"],
      ["quantity", "こすう", "個数", "kosuu", "noun", "", "kosū"],
      ["large size", "おおきいサイズ", "大きいサイズ", "ookii saizu", "noun", "", "ōkii saizu"],
      ["medium size", "ちゅうサイズ", "中サイズ", "chuu saizu", "noun", "", "chū saizu"],
      ["small size", "ちいさいサイズ", "小さいサイズ", "chiisai saizu"],
      ["black", "くろ", "黒", "kuro"],
      ["white", "しろ", "白", "shiro"],
      ["red", "あか", "赤", "aka"],
      ["blue", "あお", "青", "ao"],
      ["gift", "プレゼント", "プレゼント", "purezento"],
      ["souvenir", "おみやげ", "お土産", "omiyage"],
      ["local product", "とくさんひん", "特産品", "tokusanpin"],
      ["clothes", "ふく", "服", "fuku"],
      ["shoes", "くつ", "靴", "kutsu"],
      ["electronics", "でんかせいひん", "電化製品", "denka seihin"],
      ["cosmetics", "けしょうひん", "化粧品", "keshouhin", "noun", "", "keshōhin"],
      ["medicine", "くすり", "薬", "kusuri"],
      ["queue", "れつ", "列", "retsu"],
      ["shopping basket", "かいものかご", "買い物かご", "kaimono kago"],
      ["shopping cart", "カート", "カート", "kaato", "noun", "", "kāto"],
      ["delivery", "はいたつ", "配達", "haitatsu"],
      ["business hours", "えいぎょうじかん", "営業時間", "eigyou jikan", "noun", "", "eigyō jikan"],
      ["consumption tax", "しょうひぜい", "消費税", "shouhizei", "noun", "", "shōhizei"],
      ["tax-inclusive price", "ぜいこみかかく", "税込価格", "zeikomi kakaku"],
      ["pre-tax price", "ぜいぬきかかく", "税抜価格", "zeinuki kakaku"],
      ["tax-free counter", "めんぜいカウンター", "免税カウンター", "menzei kauntaa", "noun", "", "menzei kauntā"],
      ["tax refund", "かんぷ", "還付", "kanpu"],
      ["refund method", "かんぷほうしき", "還付方式", "kanpu houshiki", "noun", "", "kanpu hōshiki"],
      ["original passport", "パスポートげんぽん", "パスポート原本", "pasupooto genpon", "noun", "", "pasupōto genpon"],
      ["eligibility", "たいしょうじょうけん", "対象条件", "taishou jouken", "noun", "", "taishō jōken"],
      ["barcode", "バーコード", "バーコード", "baakoodo", "noun", "", "bākōdo"],
      ["self-checkout", "セルフレジ", "セルフレジ", "serufu reji"],
      ["contactless payment", "タッチけっさい", "タッチ決済", "tacchi kessai"],
      ["cashless payment", "キャッシュレスけっさい", "キャッシュレス決済", "kyasshuresu kessai"],
      ["card declined", "カードがつかえません", "カードが使えません", "kaado ga tsukaemasen", "phrase", "", "kādo ga tsukaemasen"],
      ["return policy", "へんぴんきてい", "返品規定", "henpin kitei"],
      ["exchange deadline", "こうかんきげん", "交換期限", "koukan kigen", "noun", "", "kōkan kigen"],
      ["defective item", "ふりょうひん", "不良品", "furyouhin", "noun", "", "furyōhin"],
      ["out of stock", "ざいこぎれ", "在庫切れ", "zaikogire"],
      ["restock", "さいにゅうか", "再入荷", "sainyuuka", "noun", "", "sainyūka"],
      ["home delivery", "たくはい", "宅配", "takuhai"],
      ["delivery date", "はいたつび", "配達日", "haitatsubi"]
    ),
    slotMeanings: [
      "product", "price", "tax", "receipt", "shopping bag", "gift wrapping", "size", "color", "stock", "sample", "warranty",
      "return policy", "exchange deadline", "payment", ["credit card", "credit-card payment"],
      ["IC payment", "IC-payment option"], ["QR payment", "QR-payment option"], "discount", "coupon", "point card",
      ["delivery", "delivery service"], "business hours", "tax-free counter", ["home delivery", "home-delivery service"]
    ],
    dialogues: [
      dialogue("shopping-size", "Finding a size", "In a clothing store", [
        ["traveler", "Do you have this in a larger size?", "これの大きいサイズはありますか。", "これの大きいサイズ、ある？"],
        ["local", "Yes, I will check the stock.", "はい、在庫を確認します。", "うん、在庫を確認するね。"],
        ["traveler", "May I try it on?", "試着してもいいですか。", "試着してもいい？"],
        ["local", "The fitting room is over there.", "試着室はあちらです。", "試着室はあそこ。"]
      ]),
      dialogue("shopping-taxfree", "Tax-free shopping", "At a department store", [
        ["traveler", "Is this purchase eligible for tax-free shopping?", "この買い物は免税の対象ですか。", "この買い物、免税の対象？"],
        ["local", "Please take the items to the tax-free counter.", "商品を免税カウンターへお持ちください。", "商品を免税カウンターへ持って行って。"],
        ["traveler", "Is the original passport required?", "パスポートの原本が必要ですか。", "パスポートの原本が必要？"],
        ["local", "Yes, please bring the original.", "はい、原本をお持ちください。", "うん、原本を持って来て。"]
      ]),
      dialogue("shopping-payment", "Paying", "At the checkout", [
        ["local", "Would you like a bag?", "袋はご利用ですか。", "袋は使う？"],
        ["traveler", "No, thank you. Can I pay by card?", "いいえ、結構です。カードで払えますか。", "いらない、ありがとう。カードで払える？"],
        ["local", "Yes. Please enter your PIN.", "はい。暗証番号を入力してください。", "うん。暗証番号を入れて。"],
        ["traveler", "Could I have the receipt?", "レシートをいただけますか。", "レシートをもらえる？"]
      ])
    ],
    sentence: {
      english: "I have a question about the {meaning}.",
      formal: "{term}について質問があります",
      informal: "{term}について聞きたい"
    },
    response: {
      promptFormal: "{term}について質問がありますか",
      promptInformal: "{term}について聞きたい？",
      answerFormal: "はい、{term}について質問があります",
      answerInformal: "うん、{term}について聞きたい"
    }
  }
];

export const practicalTopics = seeds.map(buildTopic);
